<?php

return [
    [
        'key'  => 'sales.shiprocket',
        'name' => 'Shiprocket Integration',
        'info' => 'Configure your Shiprocket API credentials and settings.',
        'icon' => 'settings/shipping-method.svg',
        'sort' => 5,
    ],
    [
        'key'    => 'sales.shiprocket.settings',
        'name'   => 'Settings',
        'info'   => 'Manage API Credentials and options.',
        'sort'   => 1,
        'fields' => [
            [
                'name'          => 'active',
                'title'         => 'Enable Integration',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => true,
            ],
            [
                'name'          => 'email',
                'title'         => 'Shiprocket API Email',
                'type'          => 'text',
                'validation'    => 'required_if:active,1',
                'channel_based' => true,
            ],
            [
                'name'          => 'password',
                'title'         => 'Shiprocket API Password',
                'type'          => 'password',
                'validation'    => 'required_if:active,1',
                'channel_based' => true,
            ],
            [
                'name'          => 'pickup_location',
                'title'         => 'Pickup Location Name',
                'info'          => 'Must match exactly with the Pickup Location registered in Shiprocket dashboard.',
                'type'          => 'text',
                'validation'    => 'required_if:active,1',
                'channel_based' => true,
            ],
            [
                'name'          => 'channel_id',
                'title'         => 'Shiprocket Channel ID',
                'info'          => 'Optional: The Channel ID in Shiprocket to tag these orders.',
                'type'          => 'text',
                'channel_based' => true,
            ],
            [
                'name'          => 'sandbox',
                'title'         => 'Sandbox Mode',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => true,
            ],
            [
                'name'          => 'default_weight',
                'title'         => 'Default Package Weight (kg)',
                'info'          => 'Default weight used if product weight is not specified. (e.g. 0.5)',
                'type'          => 'text',
                'validation'    => 'numeric|min:0.01',
                'default'       => '0.5',
                'channel_based' => true,
            ],
            [
                'name'          => 'default_length',
                'title'         => 'Default Package Length (cm)',
                'info'         => 'Default length used for shipping package calculations.',
                'type'          => 'text',
                'validation'    => 'numeric|min:1',
                'default'       => '10',
                'channel_based' => true,
            ],
            [
                'name'          => 'default_breadth',
                'title'         => 'Default Package Breadth (cm)',
                'info'          => 'Default breadth used for shipping package calculations.',
                'type'          => 'text',
                'validation'    => 'numeric|min:1',
                'default'       => '10',
                'channel_based' => true,
            ],
            [
                'name'          => 'default_height',
                'title'         => 'Default Package Height (cm)',
                'info'          => 'Default height used for shipping package calculations.',
                'type'          => 'text',
                'validation'    => 'numeric|min:1',
                'default'       => '10',
                'channel_based' => true,
            ],
        ],
    ],
];
